networks:
    internet:
        external: true

services:
    app:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 3000:3000
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0

    redisq:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: redisq
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: ["/bin/sh", "-c", "./bin/console redisq"]
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0

    processWars:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: redisq
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: ["/bin/sh", "-c", "./bin/queue", "processWars"]
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0
    processStats:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: redisq
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: ["/bin/sh", "-c", "./bin/queue", "processStats"]
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0

    processKillmails:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: redisq
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: ["/bin/sh", "-c", "./bin/queue", "processKillmails"]
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0

    processHistoricalStats:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: redisq
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: ["/bin/sh", "-c", "./bin/queue", "processHistoricalStats"]
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0

    processEntities:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: redisq
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: ["/bin/sh", "-c", "./bin/queue", "processEntities"]
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0

    processCampaigns:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: redisq
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: ["/bin/sh", "-c", "./bin/queue", "processCampaigns"]
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0

    processAchievements:
        image: ghcr.io/eve-kill/thessia:latest
        container_name: redisq
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: ["/bin/sh", "-c", "./bin/queue", "processAchievements"]
        networks:
            - internet
        environment:
            DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/thessia?schema=public"
            REDIS_URI: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0

    meilisearch:
        image: getmeili/meilisearch:latest
        container_name: meilisearch
        volumes:
            - ./.data/meilisearch:/meili_data
        ports:
            - 7700:7700

    redis:
        image: library/redis:latest
        container_name: redis
        volumes:
            - ./.data/redis:/data
        ports:
            - 127.0.0.1:6379:6379
        networks:
            - internet
        restart: unless-stopped

    postgres:
        image: postgres:16
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: thessia
        volumes:
            - ./.data/postgres:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:5432:5432
        networks:
            - internet
        restart: unless-stopped
