apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thessia.labels" . | nindent 4 }}
type: Opaque
data:
  # EVE Online API Credentials
  EVE_CLIENT_ID: {{ .Values.global.env.sensitive.eveClientId | b64enc | quote }}
  EVE_CLIENT_SECRET: {{ .Values.global.env.sensitive.eveClientSecret | b64enc | quote }}
  EVE_CLIENT_REDIRECT: {{ .Values.global.env.sensitive.eveClientRedirect | b64enc | quote }}
  EVE_CLIENT_ID_DEV: {{ .Values.global.env.sensitive.eveClientIdDev | b64enc | quote }}
  EVE_CLIENT_SECRET_DEV: {{ .Values.global.env.sensitive.eveClientSecretDev | b64enc | quote }}
  EVE_CLIENT_REDIRECT_DEV: {{ .Values.global.env.sensitive.eveClientRedirectDev | b64enc | quote }}

  # Discord webhooks
  BACKEND_DISCORD_URL: {{ .Values.global.env.sensitive.backendDiscordUrl | b64enc | quote }}
  DISCORD_NEW_COMMENT: {{ .Values.global.env.sensitive.discordNewComment | b64enc | quote }}
  DISCORD_REPORT_COMMENT: {{ .Values.global.env.sensitive.discordReportComment | b64enc | quote }}

  # OpenAI Moderation
  OPENAI_API_KEY: {{ .Values.global.env.sensitive.openAIAPIKey | b64enc | quote }}

  # Tenor API
  TENOR_API_KEY: {{ .Values.global.env.sensitive.tenorAPIKey | b64enc | quote }}

  # Cloudflare Analytics Token
  CLOUDFLARE_ANALYTICS_TOKEN: {{ .Values.global.env.sensitive.cloudflareAnalyticsToken | b64enc | quote }}

  # Discord bot
  BOTNAME: {{ .Values.global.env.sensitive.botName | b64enc | quote }}
  DISCORD_TOKEN: {{ .Values.global.env.sensitive.botToken | b64enc | quote }}
  DISCORD_CLIENT_ID: {{ .Values.global.env.sensitive.botClientId | toString | b64enc | quote }}
  DISCORD_IGNORED_CHANNEL_IDS: {{ .Values.global.env.sensitive.botIgnoredChannelIds | b64enc | quote }}
  DISCORD_IGNORED_GUILD_IDS: {{ .Values.global.env.sensitive.botIgnoredGuildIds | b64enc | quote }}
  AI_PROVIDER: {{ .Values.global.env.sensitive.botAIProvider | b64enc | quote }}
  BOT_OPENAI_API_KEY: {{ .Values.global.env.sensitive.botOpenAIAPIKey | b64enc | quote }}
  BOT_OPENAI_MODEL: {{ .Values.global.env.sensitive.botOpenAIModel | b64enc | quote }}
  BOT_OPENAI_MODERATION_MODEL: {{ .Values.global.env.sensitive.botOpenAIModerationModel | b64enc | quote }}
  BOT_CLAUDE_API_KEY: {{ .Values.global.env.sensitive.botClaudeAPIKey | b64enc | quote }}
  BOT_CLAUDE_MODEL: {{ .Values.global.env.sensitive.botClaudeModel | b64enc | quote }}
