{{- if .Values.serviceAccount.create -}}
# Explicitly create the service account first
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thessia.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "thessia.name" . }}
    {{- include "thessia.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---

{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "thessia.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thessia.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "thessia.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thessia.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "thessia.serviceAccountName" . }}
    namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: {{ include "thessia.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
