{{- if .Values.serviceAccount.create -}}
# Explicitly create the service account first
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thessia.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "thessia.name" . }}
    {{- include "thessia.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---

{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "thessia.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thessia.labels" . | nindent 4 }}
rules:
  # Original permissions
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  
  # Kubernetes management permissions for admin panel
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status", "services", "endpoints", "persistentvolumes", "persistentvolumeclaims", "nodes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
  
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "thessia.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thessia.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "thessia.serviceAccountName" . }}
    namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: {{ include "thessia.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
