resources:
  - namespace.yaml
  - ingress.yaml
  - .config.yaml
  # Thessia
  - thessia/deployment.yaml
  - thessia/hpa.yaml
  - thessia/service.yaml
  # Process Entities
  #- processEntities/deployment.yaml
  # Process Wars
  #- processWars/deployment.yaml
  # RedisQ
  #- redisq/deployment.yaml
  # Cron
  #- cron/cronjob.yaml

  # Define a different namespace
namespace: demo
# Define a different ingress host
patches:
  - target:
        kind: Ingress
        name: eve-kill
    patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: demo.eve-kill.com
