apiVersion: batch/v1
kind: CronJob
metadata:
    name: cron
    namespace: eve-kill
spec:
    schedule: "* * * * *"
    successfulJobsHistoryLimit: 5
    failedJobsHistoryLimit: 5
    startingDeadlineSeconds: 60
    concurrencyPolicy: Allow
    jobTemplate:
        spec:
            activeDeadlineSeconds: 3600
            template:
                spec:
                    containers:
                      - name: cron
                        image: ghcr.io/eve-kill/thessia:latest
                        imagePullPolicy: Always
                        command:
                          - /bin/sh
                          - -c
                          - |
                            ./bin/cron
                        volumeMounts:
                          - name: eve-kill-config
                            mountPath: /app/.env
                            subPath: .env
                    restartPolicy: OnFailure
                    volumes:
                      - name: eve-kill-config
                        configMap:
                            name: eve-kill-config
