{{- if and .Values.ingress.enabled .Values.imageserver.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imageserver
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thessia.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - images.eve-kill.com
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: "images.eve-kill.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: imageserver
                port:
                  number: {{ .Values.imageserver.service.port }}
{{- end }}
