{{- if .Values.imageserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: imageserver
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thessia.labels" . | nindent 4 }}
spec:
  selector:
    app: imageserver
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.imageserver.service.port }}
      targetPort: {{ .Values.imageserver.service.targetPort }}
{{- end }}
