apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: thessia
    namespace: eve-kill
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: thessia
    minReplicas: 1
    maxReplicas: 1
    metrics:
      - type: Resource
        resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 50
